//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcdAddIn.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CcdAddIn.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fühlst Du Dich bereit?.
        /// </summary>
        public static string AreYouReady {
            get {
                return ResourceManager.GetString("AreYouReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorsicht vor Optimierungen.
        /// </summary>
        public static string BewareOptimizations {
            get {
                return ResourceManager.GetString("BewareOptimizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarzer Grad.
        /// </summary>
        public static string BlackLevel {
            get {
                return ResourceManager.GetString("BlackLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfadfinderregel.
        /// </summary>
        public static string BoyscoutRule {
            get {
                return ResourceManager.GetString("BoyscoutRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Code Developer.
        /// </summary>
        public static string CleanCodeDeveloper {
            get {
                return ResourceManager.GetString("CleanCodeDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täglich reflektieren.
        /// </summary>
        public static string DailyReflection {
            get {
                return ResourceManager.GetString("DailyReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratschlag ablehnen.
        /// </summary>
        public static string DenyAdvice {
            get {
                return ResourceManager.GetString("DenyAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Repeat Yourself (DRY).
        /// </summary>
        public static string DoNotRepeatYourself {
            get {
                return ResourceManager.GetString("DoNotRepeatYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor Composition over Inheritance (FCoI).
        /// </summary>
        public static string FavorCompositionOverInheritance {
            get {
                return ResourceManager.GetString("FavorCompositionOverInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum roten Grad.
        /// </summary>
        public static string GoToRedLevel {
            get {
                return ResourceManager.GetString("GoToRedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep It Simple, Stupid (KISS).
        /// </summary>
        public static string KeepItSimpleStupid {
            get {
                return ResourceManager.GetString("KeepItSimpleStupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht schlecht, benötigst aber noch mehr Übung..
        /// </summary>
        public static string NegativeAdvice {
            get {
                return ResourceManager.GetString("NegativeAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super gemacht, bist bereit für den nächsten Grad!.
        /// </summary>
        public static string PositiveAdvice {
            get {
                return ResourceManager.GetString("PositiveAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro.
        /// </summary>
        public static string Retro {
            get {
                return ResourceManager.GetString("Retro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Cause Analysis.
        /// </summary>
        public static string RootCauseAnalysis {
            get {
                return ResourceManager.GetString("RootCauseAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfache Refaktorisierungen.
        /// </summary>
        public static string SimpleRefactorizations {
            get {
                return ResourceManager.GetString("SimpleRefactorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratschlag annehmen.
        /// </summary>
        public static string TakeAdvice {
            get {
                return ResourceManager.GetString("TakeAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionskontrolle.
        /// </summary>
        public static string VersionControl {
            get {
                return ResourceManager.GetString("VersionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm welcome message. Du bist super, Du schaffst das! Nächster Schritt: roter Grad..
        /// </summary>
        public static string WarmWelcomeMessage {
            get {
                return ResourceManager.GetString("WarmWelcomeMessage", resourceCulture);
            }
        }
    }
}
