//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcdAddIn.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CcdAddIn.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fühlst Du Dich bereit?.
        /// </summary>
        public static string AreYouReady {
            get {
                return ResourceManager.GetString("AreYouReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilnahme an Fachveranstaltungen.
        /// </summary>
        public static string AttendProfessionalEvents {
            get {
                return ResourceManager.GetString("AttendProfessionalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisierte Integrationstests.
        /// </summary>
        public static string AutomaticIntegrationtests {
            get {
                return ResourceManager.GetString("AutomaticIntegrationtests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisierte Unit Tests.
        /// </summary>
        public static string AutomaticUnitTests {
            get {
                return ResourceManager.GetString("AutomaticUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorsicht vor Optimierungen.
        /// </summary>
        public static string BewareOptimizations {
            get {
                return ResourceManager.GetString("BewareOptimizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarzer Grad.
        /// </summary>
        public static string BlackLevel {
            get {
                return ResourceManager.GetString("BlackLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfadfinderregel.
        /// </summary>
        public static string BoyscoutRule {
            get {
                return ResourceManager.GetString("BoyscoutRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Code Developer.
        /// </summary>
        public static string CleanCodeDeveloper {
            get {
                return ResourceManager.GetString("CleanCodeDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Coverage Analyse.
        /// </summary>
        public static string CodeCoverageAnalysis {
            get {
                return ResourceManager.GetString("CodeCoverageAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komplexe Refaktorisierungen.
        /// </summary>
        public static string ComplexRefactorizations {
            get {
                return ResourceManager.GetString("ComplexRefactorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenorientierung.
        /// </summary>
        public static string ComponentOrientation {
            get {
                return ResourceManager.GetString("ComponentOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Integration.
        /// </summary>
        public static string ContinousIntegration {
            get {
                return ResourceManager.GetString("ContinousIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Delivery.
        /// </summary>
        public static string ContinuousDelivery {
            get {
                return ResourceManager.GetString("ContinuousDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täglich reflektieren.
        /// </summary>
        public static string DailyReflection {
            get {
                return ResourceManager.GetString("DailyReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratschlag ablehnen.
        /// </summary>
        public static string DenyAdvice {
            get {
                return ResourceManager.GetString("DenyAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Inversion Principle.
        /// </summary>
        public static string DependencyInversionPrinciple {
            get {
                return ResourceManager.GetString("DependencyInversionPrinciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwurf und Implementation überlappen nicht.
        /// </summary>
        public static string DesignAndImplementationDoNotOverlap {
            get {
                return ResourceManager.GetString("DesignAndImplementationDoNotOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Repeat Yourself (DRY).
        /// </summary>
        public static string DoNotRepeatYourself {
            get {
                return ResourceManager.GetString("DoNotRepeatYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor Composition over Inheritance (FCoI).
        /// </summary>
        public static string FavorCompositionOverInheritance {
            get {
                return ResourceManager.GetString("FavorCompositionOverInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum roten Grad.
        /// </summary>
        public static string GoToRedLevel {
            get {
                return ResourceManager.GetString("GoToRedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation spiegelt Entwurf.
        /// </summary>
        public static string ImplementationMirrorsDesign {
            get {
                return ResourceManager.GetString("ImplementationMirrorsDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Hiding Principle.
        /// </summary>
        public static string InformationHidingPrinciple {
            get {
                return ResourceManager.GetString("InformationHidingPrinciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Segregation Principle (ISP).
        /// </summary>
        public static string InterfaceSegregationPrinciple {
            get {
                return ResourceManager.GetString("InterfaceSegregationPrinciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversion of Control Container.
        /// </summary>
        public static string InversionOfControlContainer {
            get {
                return ResourceManager.GetString("InversionOfControlContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Tracking.
        /// </summary>
        public static string IssueTracking {
            get {
                return ResourceManager.GetString("IssueTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterative Entwicklung.
        /// </summary>
        public static string IterativeDevelopment {
            get {
                return ResourceManager.GetString("IterativeDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep It Simple, Stupid (KISS).
        /// </summary>
        public static string KeepItSimpleStupid {
            get {
                return ResourceManager.GetString("KeepItSimpleStupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law of Demeter.
        /// </summary>
        public static string LawOfDemeter {
            get {
                return ResourceManager.GetString("LawOfDemeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liskov Substitution Principle.
        /// </summary>
        public static string LiskovSubstitutionPrinciple {
            get {
                return ResourceManager.GetString("LiskovSubstitutionPrinciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messen von Fehlern.
        /// </summary>
        public static string MeasureFailure {
            get {
                return ResourceManager.GetString("MeasureFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mockups (Testattrappen).
        /// </summary>
        public static string Mockups {
            get {
                return ResourceManager.GetString("Mockups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht schlecht, benötigst aber noch mehr Übung..
        /// </summary>
        public static string NegativeAdvice {
            get {
                return ResourceManager.GetString("NegativeAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Closed Principle.
        /// </summary>
        public static string OpenClosedPrinciple {
            get {
                return ResourceManager.GetString("OpenClosedPrinciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super gemacht, bist bereit für den nächsten Grad!.
        /// </summary>
        public static string PositiveAdvice {
            get {
                return ResourceManager.GetString("PositiveAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principle of Least Astonishment.
        /// </summary>
        public static string PrincipleOfLeastAstonishment {
            get {
                return ResourceManager.GetString("PrincipleOfLeastAstonishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesen, Lesen, Lesen.
        /// </summary>
        public static string ReadReadRead {
            get {
                return ResourceManager.GetString("ReadReadRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum roten Level.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro.
        /// </summary>
        public static string Retro {
            get {
                return ResourceManager.GetString("Retro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Cause Analysis.
        /// </summary>
        public static string RootCauseAnalysis {
            get {
                return ResourceManager.GetString("RootCauseAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separation of Concerns (SoC).
        /// </summary>
        public static string SeparationOfConcerns {
            get {
                return ResourceManager.GetString("SeparationOfConcerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahrung weitergeben.
        /// </summary>
        public static string ShareExperience {
            get {
                return ResourceManager.GetString("ShareExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfache Refaktorisierungen.
        /// </summary>
        public static string SimpleRefactorizations {
            get {
                return ResourceManager.GetString("SimpleRefactorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Level of Abstraction (SLA).
        /// </summary>
        public static string SingleLevelOfAbstraction {
            get {
                return ResourceManager.GetString("SingleLevelOfAbstraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Responsibility Principle (SRP).
        /// </summary>
        public static string SingleResponsibilityPrinciple {
            get {
                return ResourceManager.GetString("SingleResponsibilityPrinciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code Konventionen.
        /// </summary>
        public static string SourceCodeConventions {
            get {
                return ResourceManager.GetString("SourceCodeConventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statische Codeanalyse (Metriken).
        /// </summary>
        public static string StaticCodeAnalysis {
            get {
                return ResourceManager.GetString("StaticCodeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratschlag annehmen.
        /// </summary>
        public static string TakeAdvice {
            get {
                return ResourceManager.GetString("TakeAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell, don´t ask.
        /// </summary>
        public static string TellDontAsk {
            get {
                return ResourceManager.GetString("TellDontAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test first.
        /// </summary>
        public static string TestFirst {
            get {
                return ResourceManager.GetString("TestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionskontrolle.
        /// </summary>
        public static string VersionControl {
            get {
                return ResourceManager.GetString("VersionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm welcome message. Du bist super, Du schaffst das! Nächster Schritt: roter Grad..
        /// </summary>
        public static string WarmWelcomeMessage {
            get {
                return ResourceManager.GetString("WarmWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist nun im weißen Level - gut gemacht..
        /// </summary>
        public static string WhiteLevelText {
            get {
                return ResourceManager.GetString("WhiteLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Ain´t Gonna Need It (YAGNI).
        /// </summary>
        public static string YouAintGonnaNeedIt {
            get {
                return ResourceManager.GetString("YouAintGonnaNeedIt", resourceCulture);
            }
        }
    }
}
